@LogiTrack_HostAddress = http://localhost:5203

// Get all inventory items
GET {{LogiTrack_HostAddress}}/api/inventory/

###

// Add a new inventory item
POST {{LogiTrack_HostAddress}}/api/inventory/
Content-Type: application/json

{
  "name": "New Item",
  "quantity": 100,
  "location": "Warehouse A",
  "orderId": 5
}

###

// Delete an inventory item by ID
DELETE {{LogiTrack_HostAddress}}/api/inventory/9

###

// Get all orders
GET {{LogiTrack_HostAddress}}/api/orders/

###

// Get a specific order by ID
GET {{LogiTrack_HostAddress}}/api/orders/4

###

// Add a new order
POST {{LogiTrack_HostAddress}}/api/orders/
Content-Type: application/json

{
  "customerName": "John Doe",
  "datePlaced": "2023-10-01T12:00:00Z",
  "itemList": [
    {
      "name": "Item A",
      "quantity": 2,
      "location": "Warehouse A"
    },
    {
      "name": "Item B",
      "quantity": 5,
      "location": "Warehouse B"
    }
  ]
}

### 

// Delete an order by ID
DELETE {{LogiTrack_HostAddress}}/api/orders/12
